version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0

executors:
  python:
    docker:
      - image: circleci/python:2-node

aliases:
  - &generate-lock-file
      run:
        name: Generate lock file
        command: yarn generate-lock-entry >> yarn.lock

  - &restore-cache
      restore_cache:
        keys:
          - dependencies-cache-{{ checksum "yarn.lock" }}

  - &save-cache
      save_cache:
        paths:
          - node_modules
        key: dependencies-cache-{{ checksum "yarn.lock" }}
  
  - &restore-build-flag
      restore_cache:
        keys:
          - build-flag-{{ checksum "package.json" }}

  - &test-build-flag
      run:
        name: Exit if build flag exists
        command: |
          FILE=build.flag
          if test -f "$FILE"; then
              echo "$FILE exist"
              circleci step halt
          fi

commands:
  save-build-flag:
    steps:
      - run:
          name: Create build flag
          command: touch build.flag
      - save_cache:
          paths:
            - build.flag
          key:
            build-flag-{{ checksum "package.json" }}

  node-build-steps:
    steps:
      - checkout:
          path: ~/project
      - *restore-build-flag
      - *test-build-flag
      # Services and packages in a Workspace don't get their own
      # yarn.lock so we need to generate them manually.
      - *generate-lock-file
      - *restore-cache
      - run:
          name: Build
          command: |
            yarn
            yarn build
            rm -rf src
      - *save-cache
      - save-build-flag
  
  node-test-steps:
    steps:
      - checkout:
          path: ~/project
      - *restore-cache
      - run:
          name: Test
          command: |
            yarn
            yarn test

jobs:
  build-app:
    working_directory: /home/circleci/project/packages/app
    executor: python
    steps:
      - node-build-steps

  test-app:
    working_directory: /home/circleci/project/packages/app
    executor: python
    steps:
      - node-test-steps

  deployS3-app:
    working_directory: /home/circleci/project/packages/app
    executor: python
    steps:
      - checkout
      - *restore-cache
      - aws-s3/sync:
          from: ./packages/app/build
          to: "s3://zsalab.com"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \

workflows:
  version: 2

  deploy:
    jobs:
      - build-app
      - test-app:
          requires:
            - build-app
      - deployS3-app:
          requires:
            - test-app
          context: aws
          filters:
            branches:
              only: main
