version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.6

jobs:
  deployS3:
    docker:
      - image: 'circleci/node:latest'

    steps:
      - checkout
      - aws-s3/sync:
          from: .
          to: 's3://zsalab-site'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \
          overwrite: true

workflows:
  deploy:
    jobs:
      - deployS3
        filters:
          branches:
            only:
              - main
