version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0

executors:
  python:
    docker:
      - image: circleci/python:2-node

jobs:
  build:
    executor: python
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  test:
    executor: python
    steps:
      - run: yarn test

  deployS3:
    executor: python
    steps:
      - checkout
      - aws-s3/sync:
          from: ./build
          to: 's3://zsalab.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \

workflows:
  deploy:
    jobs:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - build
      - test:
          requires:
            - build
      - deployS3:
          requires:
            - test
          context: aws
          filters:
            branches:
              only: main
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
