version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  deployS3:
    docker:
      - image: 'circleci/python:latest'

    steps:
      - checkout
      - aws-s3/sync:
          from: ./public
          to: 's3://zsalab.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \

workflows:
  deploy:
    jobs:
      - deployS3:
          context: aws
          filters:
            branches:
              only: main
