version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0

executors:
  python:
    docker:
      - image: circleci/python:2-node

defaults:
  - &restore-cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - cache-{{ checksum "yarn.lock" }}
  - &save-cache
    save_cache:
      name: Save Yarn Package Cache
      key: cache-{{ checksum "yarn.lock" }}
      paths:
        - /home/circleci/project/node_modules
        - /home/circleci/project/build

jobs:
  build:
    executor: python
    steps:
      - checkout
      - *restore-cache
      - run:
          command: yarn
          name: Install dependencies
      - run:
          command: yarn build
          name: Compile
      - *save-cache

  test:
    executor: python
    steps:
      - checkout
      - *restore-cache
      - run: yarn test

  deployS3:
    executor: python
    steps:
      - checkout
      - *restore-cache
      - aws-s3/sync:
          from: ./build
          to: 's3://zsalab.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \

workflows:
  deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployS3:
          requires:
            - test
          context: aws
          filters:
            branches:
              only: main
